### ISSUE TITLE
Missing "sleep" and "wake" implementations?

### ISSUE THREAD

**Issue by Nico04** [adafruit/Adafruit_CircuitPython_SSD1322#14]
Why the "sleep" and "wake" method aren't implemented, like for the [SSD1306](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306/blob/82215a51b7ba3ee9d6a762e5ae81c6d46e28a450/adafruit_displayio_ssd1306.py#L100)  for instance?

**Comment by ladyada** [comment]
we haven't done it yet, if you'd like to try please submit a PR to add it :)
