### ISSUE TITLE
One third of the screen filled with noise for some reason

### ISSUE THREAD

**Issue by berkut0** [adafruit/Adafruit_CircuitPython_SSD1322#23]
I've ruled out all the obvious causes. I have connected a second screen in exactly the same way, tried different pin combinations - nothing helps. At the same time, the **terminalio** works fine and displays something. But about a third of the screen is still covered in noise.

```Adafruit CircuitPython 9.2.0 on 2024-10-28; Waveshare RP2040-Zero with rp2040```

```Python
import board, supervisor, time, terminalio
import neopixel
import busio, displayio
from adafruit_display_text import label
import adafruit_ssd1322

pixels = neopixel.NeoPixel(board.GP16, 1, auto_write=True)

displayio.release_displays()

spi2 = busio.SPI(clock=board.GP2, MOSI=board.GP3)

display_busB = displayio.FourWire(spi2, command=board.GP5, chip_select=board.GP6, reset=board.GP4, baudrate=1000000)

display = adafruit_ssd1322.SSD1322(display_busB, width=256, height=64, colstart=28)
```
![screen_issue](https://github.com/user-attachments/assets/07c27f55-d47d-49f6-888d-81d67a5f1421)

upd: I've just realised that the image seems to be shifted to the left. I'll try to work around that

**Comment by berkut0** [comment]
I think changing the ```colstart=112``` parameter helped. What is the reason for this?

**Comment by tannewt** [comment]
Different displays connect to the SSD1322 chip differently and this impacts which columns appear on the display. `colstart` is used to adjust for how the display is connected. I'd suggest adding an example for this specific display. That way the next person can start with the correct value. It isn't a bug with the library.

**Comment by rp86** [comment]
Hi, thanks for your work on this library. I wasn't sure the best way to add this example config to the docs so I thought I'd post it in this thread. 

The above colstart=112 setting worked for the following display (ordered in 4-wire SPI configuration): https://www.buydisplay.com/white-3-2-inch-arduino-raspberry-pi-oled-display-module-256x64-spi

```
display_bus = displayio.FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=tft_reset, baudrate=1000000)
time.sleep(1)
display = adafruit_ssd1322.SSD1322(display_bus, width=256, height=64, colstart=112)
```
