### ISSUE TITLE
Is there any way to draw a pixel without a bitmap?

### ISSUE THREAD

**Issue by AdinAck** [adafruit/Adafruit_CircuitPython_SSD1322#3]
I have been using this driver with my SSD1322 display and have just started making animations and have discovered it in incredibly slow because I have to recreate the group, tile_grid, and bitmap in order to update the screen. How can I draw a single pixel without using a bitmap to improve the speed?

Thanks!

EDIT: To articulate more, maybe a series of displayio.send() commands that select column and row and turn on that pixel? Lot's of register stuff that I know nothing about!
Thanks again!

**Comment by tannewt** [comment]
Hi @AdinAck, you can set the pixel value on the bitmap and it should update just that portion of the screen. Make sure you are using CircuitPython 5.x. I'm not sure that optimization is in 4.x.

**Comment by AdinAck** [comment]
Ok, thanks, good to know, I am using version 5.x so maybe I am doing something wrong? Even just drawing one pixel moving across the screen is incredibly slow because I have to recreate the group every time. If I just change the bitmap after running "group.show(group)" it will only show on the screen if the bitmap is changed a couple of fractions of a second after running the show group command. So I tried running "group.show(group)" every time I wanted to update the screen, but that doesn't work, it says the group has already been shown? So now every time I want to update the screen, I modify the bitmap then completely rebuild the group so I can display the changes, and this is an incredibly slow process. Is this not the correct way to do this?
Thanks!

**Comment by tannewt** [comment]
Please post your full code. You shouldn't have to change the group at all
once the bitmap is displaying. Setting the new pixels should cause a
limited display refresh.

**Comment by AdinAck** [comment]
Hello thanks for the help, just changing the bitmap with "bitmap[x,y] = 1" works, I was doing it wrong sorry! Thanks for the help!
